# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

name: Merge

on:
  workflow_dispatch:

  push:
    branches: [ main, dev ]
    paths:
    - 'clients/dotnet/**'
    - '.github/actions/**'
    - '!**/**.md'

  pull_request:
    branches: [ main, dev ]
    paths:
    - 'clients/dotnet/**'
    - '.github/actions/**'
    - '!**/**.md'

jobs:
  evaluate_dotnet_clients:
    name: 'Evaluating dotnet clients'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        tfm: [ net6.0, net7.0 ]
    steps:
    - uses: actions/checkout@v3
  
    - name: 'Setup .NET 6.0.x'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: 'Setup .NET 7.0.x'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: 'dotnet --info'
      run: dotnet --info

    - name: 'Build solution Microsoft.IoT.ModelsRepository.CommandLine'
      run: dotnet build clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine

    - name: 'Execute solution Microsoft.IoT.ModelsRepository.CommandLine tests'
      run: dotnet test --no-build clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine --framework ${{ matrix.tfm }} --blame-hang

    - name: 'Build solution Microsoft.IoT.ModelsRepository.ChangeCalc'
      run: dotnet build .github/actions/changecalc/Microsoft.IoT.ModelsRepository.ChangeCalc/src

    - name: 'Execute solution Microsoft.IoT.ModelsRepository.ChangeCalc tests'
      run: dotnet test --no-build --verbosity detailed .github/actions/changecalc/Microsoft.IoT.ModelsRepository.ChangeCalc/tests --framework ${{ matrix.tfm }} --blame-hang

  evaluate_python_tools:
    name: Evaluating python tools
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.x'
        architecture: 'x64'
    - run: python -m pip install -r .github/workflows/action-test-artifacts/validate-models/requirements &&
        pytest -v .github/workflows/action-test-artifacts/validate-models/test_process.py --cov=process
